### ISSUE TITLE
Colons make text bold

### ISSUE THREAD

**Issue by msmeeks** [jwilcurt-salesforce-com/gus-markdown#31]
While editing a User Story when I include a colon it turns text from the beginning of the line up to the colon bold.

Ex.

From client: details...

Is rendered

**From client:** details...

**Comment by jwilcurt-salesforce-com** [comment]
Yes, that was done intentionally. There are a lot of patterns that the extension detects and then reformats to to attempt to improve readibility from those who are not using markdown or the extension.

for example:
```
1 ) asdf
2 ) asdf
3 ) asdf
```
will be converted to
```
1. asdf
1. asdf
1. asdf
```
on page load so that it is rendered as an actual numbered list.
1. asdf
1. asdf
1. asdf

In almost every case we found, when the first few words of a line are followed by a colon, it is meant as a declaration of the type of content to come.

Such as

```
Steps to Reproduce:
1. asdf
2. asdf
3. asdf

Expected: asdf asdf asdf asdf
Actual: asdf asdf asdf asdf
```

Or in your case, declaring the type of information to follow as being "From a client". So to improve readability, those are automatically bolded to typographically differentiate the purpose and meaning of the text.

**Steps to Reproduce:**
1. asdf
2. asdf
3. asdf

**Expected:** asdf asdf asdf asdf
**Actual:** asdf asdf asdf asdf
